version: '3.8'

#defines containers we want to run
services:

  postgres:
    image: postgres:15
    container_name: placement-postgres
    restart: always
    #enc var - initialized the db automatically
    environment:
      POSTGRES_DB: placement_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    #keeps the data 'persistent' - data isn't lost when the container is stoped or lost
    volumes:
      - postgres_data:/var/lib/postgresql/data

  #gives web ui to manage the db
  pgadmin:
    image: dpage/pgadmin4
    container_name: placement-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@placement.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  postgres_data: